services:
  - type: web
    name: sare-faceit-bot
    env: python
    region: frankfurt
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: LOG_CHAT_ID
        sync: false
      - key: REQUIRED_CHANNEL_2_ID
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: LOG_THREAD_ID
        value: "0"
      - key: RESULTS_THREAD_ID
        value: "0"
      - key: PORT
        value: "8099"
